sonar.projectKey=mytime_official
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.ruleKey=xml:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e3.resourceKey=**
sonar.issue.ignore.multicriteria.e4.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e4.resourceKey=**
sonar.issue.ignore.multicriteria.e5.ruleKey=python:S2245
sonar.issue.ignore.multicriteria.e5.resourceKey=**
sonar.issue.ignore.multicriteria.e6.ruleKey=Web:S6850
sonar.issue.ignore.multicriteria.e6.resourceKey=**
sonar.python.version=3.9, 3.10, 3.11
sonar.python.coverage.reportPaths=coverage-reports/*coverage-*.xml
sonar.exclusions=tests/**,migrations/**,scripts/experimental/**,**/description/index.html,*.cjs,**/base_geoengine/static/src/**,**/lib/**,**/base_geoengine_demo/**,**/__manifest__.py
# Disable SCM (Git blame) analysis to avoid MissingObjectException
sonar.scm.disabled=true
